In [1]:
import numpy
import talib

In [2]:
#All of the following examples use the Function API:
close = numpy.random.random(100)
close

array([ 0.4387554 ,  0.21719576,  0.2341065 ,  0.10936348,  0.12718426,
        0.84089717,  0.8361427 ,  0.58079241,  0.09661679,  0.20815604,
        0.75959555,  0.37778276,  0.04179488,  0.65779953,  0.38453752,
        0.71886486,  0.36027865,  0.92429876,  0.10991904,  0.11966543,
        0.28321401,  0.29194084,  0.4451173 ,  0.34893841,  0.66328099,
        0.32424816,  0.17706083,  0.21195583,  0.95872089,  0.94930114,
        0.00348171,  0.29745537,  0.65898167,  0.33522185,  0.04794617,
        0.26621108,  0.38134697,  0.10257987,  0.83297617,  0.92293163,
        0.15836562,  0.16483147,  0.18893293,  0.17954397,  0.4435581 ,
        0.14349433,  0.17285343,  0.97743965,  0.38442193,  0.04467842,
        0.13198759,  0.55732909,  0.29547308,  0.67986773,  0.85791567,
        0.63368384,  0.1595902 ,  0.34150161,  0.10275769,  0.12680156,
        0.92084646,  0.32582104,  0.30230982,  0.96800735,  0.71899874,
        0.3108176 ,  0.67500703,  0.1257898 ,  0.47860292,  0.45

In [3]:
# Calculate a simple moving average of the close prices:
output = talib.SMA(close)
output

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,  0.4265842 ,
        0.41207507,  0.41475039,  0.4289129 ,  0.43644151,  0.43380024,
        0.41464404,  0.39948418,  0.38354376,  0.40808908,  0.43191493,
        0.41187393,  0.40477556,  0.40968016,  0.39373831,  0.39570566,
        0.37652664,  0.37027913,  0.3720505 ,  0.38120059,  0.37870103,
        0.37366014,  0.38250642,  0.37751828,  0.38854926,  0.39503708,
        0.4053516 ,  0.40476925,  0.40908744,  0.38055533,  0.35313868,
        0.38371751,  0.38466303,  0.37277397,  0.39386682,  0.41623523,
        0.41772212,  0.42751079,  0.42828445,  0.41647201,  0.40

In [14]:
# Calculating bollinger bands, with triple exponential moving average:
from talib import MA_Type

upper, middle, lower = talib.BBANDS(close, matype=MA_Type.T3)
upper

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,  1.11979974,
        1.16568696,  1.12928323,  1.12534776,  1.09624934,  1.20365608,
        1.05187961,  1.02226403,  0.95779026,  0.92295093,  0.86808095,
        0.83734777,  0.97856275,  1.02465193,  1.08342538,  0.82188123,
        0.84885517,  0.80601977,  1.03780961,  1.19896681,  1.25789361,
        1.297045  ,  1.49145557,  1.41243799,  1.36939757,  1.25594876,
        0.96074352,  1.13458446,  1.28274869,  1.35613618,  1.41119401,
        1.34965155,  1.39701069,  1.44125337,  0.91491483,  1.17994723,
        1.13346979,  1.03594478,  0.97912365,  0.74849257,  0.96522032,
        0.9598674 ,  1.1901109 ,  1.25072494,  1.12986236,  1.34

In [15]:
# Calculating momentum of the close prices, with a time period of 5:
output = talib.MOM(close, timeperiod=5)
output

array([        nan,         nan,         nan,         nan,         nan,
       -0.44684386, -0.20468384,  0.44232397, -0.32917354, -0.47210538,
        0.60584711,  0.72707005, -0.68478408,  0.61938276,  0.09692448,
       -0.79343242, -0.51316766,  0.46720997, -0.34609731, -0.51666531,
        0.73820543,  0.50340243,  0.14475782, -0.24805027,  0.47592963,
       -0.79850264, -0.02684587, -0.07176724,  0.35884791, -0.49270238,
        0.48204992, -0.63040295, -0.109674  , -0.29106777,  0.00413748,
       -0.0315344 ,  0.71903903, -0.09696155,  0.39627087,  0.48108046,
       -0.03817846, -0.53847293,  0.36354751,  0.28679665,  0.28296633,
        0.45696856, -0.3104578 , -0.18987895, -0.770745  , -0.59893925,
       -0.891953  ,  0.99151608,  0.1593163 , -0.18447532,  0.67587153,
        0.91380516, -0.20103439, -0.11890613,  0.79228011, -0.5142948 ,
       -0.58340903, -0.29093147, -0.74972994, -0.75721256,  0.50912457,
       -0.08663126,  0.44231434,  0.76729109,  0.89226776, -0.71

In [16]:
"""
If you're already familiar with using the function API, you should feel right at home using the Abstract API.

Every function takes a collection of named inputs, either a dict of numpy.ndarray or pandas.Series, or a pandas.DataFrame. If a pandas.DataFrame is provided, the output is returned as a pandas.DataFrame with named output columns.

For example, inputs could be provided for the typical "OHLCV" data:
"""

import numpy as np

# note that all ndarrays must be the same length!
inputs = {
    'open': np.random.random(100),
    'high': np.random.random(100),
    'low': np.random.random(100),
    'close': np.random.random(100),
    'volume': np.random.random(100)
}

In [18]:
#Functions can either be imported directly or instantiated by name:

from talib import abstract

# directly
sma = abstract.SMA

# or by name
sma = abstract.Function('sma')
sma

{'function_flags': ['Output scale same as input'], 'parameters': OrderedDict([('timeperiod', 30)]), 'display_name': 'Simple Moving Average', 'output_names': ['real'], 'input_names': OrderedDict([('price', 'close')]), 'output_flags': OrderedDict([('real', ['Line'])]), 'group': 'Overlap Studies', 'name': 'SMA'}

In [25]:
# From there, calling functions is basically the same as the function API:

from talib.abstract import *

# uses close prices (default)
output = SMA(inputs, timeperiod=25)

# uses open prices
output = SMA(inputs, timeperiod=25, price='open')

# uses close prices (default)
upper, middle, lower = BBANDS(inputs, 20, 2, 2)

# uses high, low, close (default)
slowk, slowd = STOCH(inputs, 5, 3, 0, 3, 0) # uses high, low, close by default

# uses high, low, open instead
slowk, slowd = STOCH(inputs, 5, 3, 0, 3, 0, prices=['high', 'low', 'open'])

output

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,  0.45476786,
        0.4752356 ,  0.4801881 ,  0.47874359,  0.48668607,  0.46837146,
        0.48593577,  0.46472362,  0.46460062,  0.4731309 ,  0.46979732,
        0.44333119,  0.44073606,  0.42485317,  0.42906862,  0.39827261,
        0.41067347,  0.43716778,  0.43492717,  0.41033979,  0.40563585,
        0.40944925,  0.41768505,  0.42060535,  0.42643175,  0.42143711,
        0.39912874,  0.4051253 ,  0.41568892,  0.40472965,  0.4052608 ,
        0.40980482,  0.44107123,  0.45423019,  0.43193521,  0.43376752,
        0.45543078,  0.47902237,  0.48406613,  0.48427482,  0.49182892,
        0.4880147 ,  0.47375691,  0.45950775,  0.47037125,  0.47

In [22]:
"""
Supported Indicators and Functions
-- --------------------------------------
We can show all the TA functions supported by TA-Lib, 
either as a list or as a dict sorted by group 
(e.g. "Overlap Studies", "Momentum Indicators", etc):
"""
import talib

# list of functions
print talib.get_functions()

# dict of functions by group
print talib.get_function_groups()

SyntaxError: invalid syntax (<ipython-input-22-842b54579cad>, line 11)

In [28]:
# test..... :)

WILLR

{'function_flags': None, 'parameters': OrderedDict([('timeperiod', 25)]), 'display_name': "Williams' %R", 'output_names': ['real'], 'input_names': OrderedDict([('prices', ['high', 'low', 'close'])]), 'output_flags': OrderedDict([('real', ['Line'])]), 'group': 'Momentum Indicators', 'name': 'WILLR'}

In [32]:
output = WILLR(inputs, timeperiod=25)
output

array([          nan,           nan,           nan,           nan,
        -58.58741585,  -25.28905738,  -72.39876517,  -65.95055634,
        -33.79289972,   -3.26638722,  -73.35437678,  -98.35800146,
        -88.61014748,  -11.17323091,  -13.63530895,    3.96938166,
       -273.35422962,  -58.54233545, -188.38233192, -281.70938411,
        -89.49504317, -104.7782473 ,  -22.87039968,  -94.04781637,
        -57.00015077,  -89.15504432,  -37.64100403,  -42.24718457,
        -78.4422811 ,  -68.02575321,  -98.5554582 ,   -6.2410591 ,
        -20.19780846,  -48.81448562,  -20.58672017,  -93.19479055,
        -34.10886753,  -34.61901635,  -62.33557235,  -25.22779146,
        -35.52445501,  -90.55535616,   -2.142366  ,  -52.78157187,
        -77.85309048,  -23.36343578,  -21.61769141,   16.6922644 ,
       -109.46859741,  -57.62620851,  -49.35885911, -101.64316299,
         -8.00318712,  -37.3941785 ,  -95.62242137,    8.10794554,
         14.58863499,   44.08922377,  -87.1917715 ,  -19.45616